CHECKINS_LOGGER     = Logger.new("log/checkins.#{Rails.env}.log")
EXCEPTIONS_LOGGER   = Logger.new("log/exceptions.#{Rails.env}.log")
LOCATIONS_LOGGER    = Logger.new("log/locations.#{Rails.env}.log")
SUGGESTIONS_LOGGER  = Logger.new("log/suggestions.#{Rails.env}.log")
USERS_LOGGER        = Logger.new("log/users.#{Rails.env}.log")
