Time::DATE_FORMATS[:datetime]                   = "%B %d, %Y at %I:%M %p"         # October 31, 2008 at 5:15 pm
Time::DATE_FORMATS[:datetime_short]             = "%b %d, %Y at %I:%M %p"         # Oct 31, 2008 at 5:15 pm
Time::DATE_FORMATS[:datetime_dow]               = "%A, %B %d, %Y at %I:%M %p"     # Friday, October 31, 2008 at 5:15 pm
Time::DATE_FORMATS[:datetime_army]              = "%b %d %Y %H%M"                 # October 31 2008 1715
Time::DATE_FORMATS[:datetime_schedule]          = "%Y%m%dT%H%M%S"                 # 20081031T120000
Time::DATE_FORMATS[:datetime_compact]           = "%Y%m%dT%H%M%S"                 # 20081031T120000
Time::DATE_FORMATS[:date_ddmmyyyy]              = "%m/%d/%Y"                      # 2/13/2011
Time::DATE_FORMATS[:date_yyyymmdd]              = "%Y%m%d"                        # 20110213
Time::DATE_FORMATS[:date_dow_ddmmyyyy]          = "%a %m/%d/%Y"                   # Fri 2/13/2011
