development:
  port: 7312
  max_matches: 200
  max_children: 5   # default is unlimited
  read_timeout: 5   # default is 5 seconds
  mlock: 0          # set mlock = 1 to keep .spa and .spi files in ram
  pid_file: log/searchd.development.pid
  # ignore single quotes
  ignore_chars: U+0027
  morphology: stem_en
production:
  port: 3312
  max_matches: 200
  # ignore single quotes
  ignore_chars: U+0027
  # file paths, pid file
  searchd_file_path: /usr/apps/social/shared/sphinx
  searchd_log_file: /usr/apps/social/current/log/searchd.log
  query_log_file: /usr/apps/social/current/log/searchd.query.log
  pid_file:  /usr/apps/social/current/log/searchd.production.pid
  # indexer memory limit
  mem_limit: 128M
  morphology: stem_en
staging:
  port: 3312
  max_matches: 200
  # ignore single quotes
  ignore_chars: U+0027
  # file paths, pid file
  searchd_file_path: /usr/apps/social/shared/sphinx
  searchd_log_file: /usr/apps/social/current/log/searchd.log
  query_log_file: /usr/apps/social/current/log/searchd.query.log
  pid_file:  /usr/apps/social/current/log/searchd.production.pid
  # indexer memory limit
  mem_limit: 128M
  morphology: stem_en
test:
  port: 7313
  max_matches: 200
  searchd_log_file: log/searchd.test.log
  query_log_file: log/searchd.query.test.log
  pid_file: log/searchd.test.pid
  # ignore single quotes
  ignore_chars: U+0027
  morphology: stem_en
