#!/usr/bin/env ruby
require "rubygems"
require "net/sftp"

# credentials
server      = "184.106.153.243" # outapp1
user        = "app"
app         = "outlately"

today       = Time.now.strftime("%Y%m%d")
backup_path = "/usr/apps/#{app}/shared/backups"
backups     = []
environment = ENV["RAILS_ENV"] || "development"

# check environment
if environment == 'production'
  puts "#{Time.now}: not allowed in production environment"
  exit
end

puts "#{Time.now}: searching for backups ..."

Net::SFTP.start(server, user, :port => 22) do |sftp|
  sftp.dir.foreach(backup_path) do |entry|
    # keep backups made today
    next unless entry.name.match(/#{app}_production_#{today}/)
    backups.push(entry.name)
  end

  # find most recent backup
  backup = backups.sort_by{ |s| s }.last

  if backup.nil?
    puts "#{Time.now}: no backup found"
    exit
  end

  puts "#{Time.now}: downloading backup: #{backup}"
  sftp.download!("#{backup_path}/#{backup}", backup)
  puts "#{Time.now}: restoring backup to #{app}_#{environment} database"
  system "rake db:restore DB=#{app}_#{environment} FILE=#{backup}"
  # system "rake ts:rebuild"
end

